window_title = "Creator 2000 :)"
input_order_number = "Zadaj číslo objednávky:"
load_order = "Načítaj objednávku"
alert_text = "!!!!!!! Skontroluj, ocisti a uloz vygenerovany TXT subor. !!!!!!!"
done = "HOTOVO 😀"
confirm_text = "Podtvrď zmeny a pokračuj"
